# Generated by Django 4.2.7 on 2024-09-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailrefund',
            old_name='order_id',
            new_name='order',
        ),
    ]
