# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0002_initial'),
        ('retail_logistics', '0002_initial'),
        ('retail_orders', '0002_initial'),
        ('retail_refund', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundproductstatus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundproductstatus',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to='retail_logistics.deliverydriver'),
        ),
        migrations.AddField(
            model_name='refundproductstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_refund.refundstatus'),
        ),
        migrations.AddField(
            model_name='retailrefund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_orders.retailorder'),
        ),
        migrations.AddField(
            model_name='retailrefund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailrefunditem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_refund', to='retail.retailproductsvariations'),
        ),
        migrations.AddField(
            model_name='retailrefund',
            name='refund_products',
            field=models.ManyToManyField(related_name='refunds', to='retail_refund.retailrefunditem'),
        ),
        migrations.AddField(
            model_name='refundproductstatus',
            name='refund_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to='retail_refund.retailrefunditem'),
        ),
    ]
