# Generated by Django 4.2.7 on 2024-09-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_remove_productsvariationsimage_variation_and_more'),
        ('retail_refund', '0002_rename_order_id_retailrefund_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrefunditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_refund', to='retail.retailproductsvariations'),
        ),
    ]
