# Generated by Django 4.2.7 on 2024-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0003_alter_retailrefunditem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailrefunditem',
            old_name='product',
            new_name='product_variation',
        ),
        migrations.AlterField(
            model_name='retailrefunditem',
            name='image_1',
            field=models.ImageField(null=True, upload_to='refund-products/'),
        ),
    ]
