# Generated by Django 4.2.7 on 2024-09-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0004_rename_product_retailrefunditem_product_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrefunditem',
            name='image_1',
            field=models.ImageField(upload_to='refund-products/'),
        ),
    ]
