# Generated by Django 4.2.7 on 2024-09-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0008_orderedproduct_vendor_order_and_more'),
        ('retail_refund', '0005_alter_retailrefunditem_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrefund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_orders.retailorder'),
        ),
    ]
