# Generated by Django 4.2.7 on 2024-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0006_alter_retailrefund_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrefunditem',
            name='image_1',
            field=models.ImageField(null=True, upload_to='refund-products/'),
        ),
    ]
