# Generated by Django 4.2.7 on 2024-09-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0007_alter_retailrefunditem_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='retailrefunditem',
            name='status',
        ),
        migrations.CreateModel(
            name='RefundProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to='retail_refund.retailrefunditem')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_refund.refundstatus')),
            ],
        ),
    ]
