# Generated by Django 4.2.7 on 2024-09-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0009_refundproductstatus_delivery_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundstatus',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
