# Generated by Django 4.2.7 on 2024-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0010_refundstatus_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundstatus',
            name='closed',
        ),
        migrations.AddField(
            model_name='refundproductstatus',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
