# Generated by Django 4.2.7 on 2024-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0011_remove_refundstatus_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundstatus',
            name='status_code',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
