# Generated by Django 4.2.7 on 2024-09-12 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail_refund', '0012_refundstatus_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundstatus',
            name='created_by',
        ),
        migrations.AddField(
            model_name='refundproductstatus',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
