# Generated by Django 4.2.7 on 2024-09-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_logistics', '0004_deliverydriverstatus_created_by_and_more'),
        ('retail_refund', '0013_remove_refundstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproductstatus',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_status', to='retail_logistics.deliverydriver'),
        ),
    ]
