# Generated by Django 4.2.7 on 2024-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0015_alter_refundstatus_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundstatus',
            name='status_code',
            field=models.CharField(max_length=100),
        ),
    ]
