# Generated by Django 4.2.7 on 2024-11-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_refund', '0017_alter_refundstatus_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproductstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
