# Generated by Django 4.2.7 on 2024-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriver',
            name='license_image',
            field=models.ImageField(null=True, upload_to='license_image/'),
        ),
    ]
