# Generated by Django 4.2.7 on 2024-09-10 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retail_logistics', '0002_deliverydriver_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriverlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydriverlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliverydriverstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydriverstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
