# Generated by Django 4.2.7 on 2024-09-11 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail_logistics', '0003_deliverydriverlocation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriverstatus',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_status', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydriverstatus',
            name='status_code',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
