# Generated by Django 4.2.7 on 2024-11-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_logistics', '0005_deliveryboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoundaryKmlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kml_file', models.FileField(upload_to='kml_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryboundary',
            name='kml_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boundary_kml_file', to='retail_logistics.deliveryboundarykmlfile'),
            preserve_default=False,
        ),
    ]
