# Generated by Django 4.2.16 on 2024-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_review', '0002_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
