# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.fooditem'),
        ),
    ]
