# Generated by Django 5.0 on 2024-02-24 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_cart_special_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartaddons",
            name="addons",
        ),
    ]
