# Generated by Django 5.0 on 2024-02-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_remove_cartaddons_addons"),
        ("menu", "0017_remove_foodaddonscategory_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartaddons",
            name="customization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_menu",
                to="menu.customization",
            ),
        ),
    ]
