# Generated by Django 5.0 on 2024-03-05 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cartaddons_customization'),
        ('menu', '0019_alter_customizationtitle_select_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='receiver_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.fooditem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoodCustomizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_request', models.CharField(max_length=255)),
                ('receiver_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_addons', to='marketplace.cart')),
                ('customization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_menu', to='menu.customization')),
            ],
        ),
        migrations.DeleteModel(
            name='CartAddons',
        ),
    ]
