# Generated by Django 5.0 on 2024-03-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_cart_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcustomizations',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='foodcustomizations',
            name='special_request',
        ),
    ]
