# Generated by Django 5.1.4 on 2024-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('offer_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='platform_offers_banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(choices=[('IN AMOUNT', 'IN AMOUNT'), ('IN PERCENTAGE', 'IN PERCENTAGE')], default='IN AMOUNT', help_text='\n        ("IN AMOUNT","IN AMOUNT"),\n        ("IN PERCENTAGE","IN PERCENTAGE")\n        ')),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('coupons_title', models.CharField(max_length=255)),
                ('coupon_code', models.CharField(help_text='max length = 25', max_length=25, unique=True)),
                ('coupon_type', models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Off', 'Percentage Off'), ('Delivery Fee  off', 'Delivery Fee  off')], help_text='\n        ("Flat Discount","Flat Discount"),\n        ("Percentage Off","Percentage Off"),\n        ("Delivery Fee  off","Delivery Fee  off")\n                                   ')),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('limitation_for_user', models.IntegerField()),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('coupon_usage_limitation', models.IntegerField(default=0)),
                ('chowchow_coupon', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('usage', models.IntegerField(default=0, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailFreeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('offer_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount_banner', models.ImageField(blank=True, null=True, upload_to='free_delivery/')),
                ('active', models.BooleanField(default=True)),
                ('minimum_spend_amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailGetOneFreeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailLoyaltyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=255, null=True, unique=True)),
                ('no_of_points', models.IntegerField()),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailSaveOnItemsDiscountPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentages', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetailSaveOnItemsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255, null=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailStoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('discount_percentages', models.FloatField(default=0)),
                ('minimum_spend_amount', models.FloatField(default=0)),
                ('maximum_redeem_value', models.FloatField(default=0, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPlatformOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentages', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_slug', models.SlugField()),
                ('category_description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('categories_order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='department/')),
                ('products', models.ManyToManyField(related_name='offer_categories', to='retail.retailproducts')),
            ],
        ),
    ]
