# Generated by Django 4.2.7 on 2024-08-02 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0026_customization_customization_order'),
        ('retail', '0010_alter_retailproducts_image_1_and_more'),
        ('vendor', '0014_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('discount_percentages', models.FloatField(default=0)),
                ('minimum_spend_amount', models.FloatField(default=0)),
                ('maximum_redeem_value', models.FloatField(default=0, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_offers', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailSaveOnItemsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255, null=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailSaveOnItemsDiscountPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentages', models.FloatField(default=0)),
                ('retail_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproducts')),
                ('store_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='retail_offers.retailsaveonitemsoffer')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='menu.vendorcategories')),
            ],
        ),
        migrations.CreateModel(
            name='RetailGetOneFreeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='reatil_offers_banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('retail_products', models.ManyToManyField(to='retail.retailproducts')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_one_free_offers', to='vendor.vendor')),
            ],
        ),
    ]
