# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_initial'),
        ('retail', '0002_initial'),
        ('retail_offers', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offercategory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_categories', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='platformoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailcoupon',
            name='vendor',
            field=models.ManyToManyField(related_name='retail_coupons', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='retailfreedelivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailgetonefreeoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailgetonefreeoffer',
            name='retail_products',
            field=models.ManyToManyField(related_name='bogo', to='retail.retailproducts'),
        ),
        migrations.AddField(
            model_name='retailgetonefreeoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_one_free_offers', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='offer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='retail_offers.offercategory'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='retail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproducts'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='retail_product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproductsvariations'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='menu.vendorcategories'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='store_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='retail_offers.retailsaveonitemsoffer'),
        ),
        migrations.AddField(
            model_name='retailstoreoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailstoreoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_offers', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='platform_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail_offers.platformoffer'),
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='retail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail.retailproducts'),
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='retail_product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail.retailproductsvariations'),
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='vendor.vendor'),
        ),
    ]
