# Generated by Django 4.2.7 on 2024-08-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_alter_retailproducts_image_1_and_more'),
        ('retail_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='retail_product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproductsvariations'),
        ),
    ]
