# Generated by Django 4.2.7 on 2024-08-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0014_faqs'),
        ('retail_offers', '0002_retailsaveonitemsdiscountpercentage_retail_product_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='max length = 25', max_length=25, unique=True)),
                ('discount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(choices=[('IN AMOUNT', 'IN AMOUNT'), ('IN PERCENTAGE', 'IN PERCENTAGE')], default='IN AMOUNT', help_text='\n        ("IN AMOUNT","IN AMOUNT"),\n        ("IN PERCENTAGE","IN PERCENTAGE")\n        ')),
                ('coupon_type', models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Off', 'Percentage Off'), ('Delivery Fee  off', 'Delivery Fee  off')], help_text='\n        ("Flat Discount","Flat Discount"),\n        ("Percentage Off","Percentage Off"),\n        ("Delivery Fee  off","Delivery Fee  off")\n                                   ')),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('limitation_for_user', models.IntegerField()),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_coupons', to='vendor.vendor')),
            ],
        ),
    ]
