# Generated by Django 4.2.7 on 2024-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0004_retailcoupon_created_date_retailcoupon_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailcoupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='retailcoupon',
            old_name='title',
            new_name='coupons_title',
        ),
        migrations.RenameField(
            model_name='retailcoupon',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='retailcoupon',
            name='discount_percentages',
            field=models.FloatField(default=0.0),
        ),
    ]
