# Generated by Django 4.2.7 on 2024-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0014_faqs'),
        ('retail_offers', '0005_rename_code_retailcoupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailcoupon',
            name='vendor',
        ),
        migrations.AddField(
            model_name='retailcoupon',
            name='vendor',
            field=models.ManyToManyField(related_name='retail_coupons', to='vendor.vendor'),
        ),
    ]
