# Generated by Django 4.2.7 on 2024-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0006_remove_retailcoupon_vendor_retailcoupon_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcoupon',
            name='coupon_usage_limitation',
            field=models.IntegerField(default=0),
        ),
    ]
