# Generated by Django 4.2.7 on 2024-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0007_retailcoupon_coupon_usage_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcoupon',
            name='chowchow_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
