# Generated by Django 4.2.7 on 2024-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0008_retailcoupon_chowchow_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailLoyaltyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=255, null=True, unique=True)),
                ('no_of_points', models.IntegerField()),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
