# Generated by Django 4.2.7 on 2024-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0009_retailloyaltyprograms'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcoupon',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
