# Generated by Django 4.2.7 on 2024-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0010_retailcoupon_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailcoupon',
            name='usage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
