# Generated by Django 4.2.7 on 2024-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0015_alter_refundpolicy_description'),
        ('retail_offers', '0011_alter_retailcoupon_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailgetonefreeoffer',
            name='retail_products',
            field=models.ManyToManyField(related_name='bogo', to='retail.retailproducts'),
        ),
    ]
