# Generated by Django 4.2.7 on 2024-09-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_remove_retailproducts_sub_category_and_more'),
        ('vendor', '0014_faqs'),
        ('retail_offers', '0012_alter_retailgetonefreeoffer_retail_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_slug', models.SlugField()),
                ('category_description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('categories_order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='department/')),
                ('products', models.ManyToManyField(related_name='offer_categories', to='retail.retailproducts')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_categories', to='vendor.vendor')),
            ],
        ),
    ]
