# Generated by Django 4.2.7 on 2024-09-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0013_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='offer_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='retail_offers.offercategory'),
        ),
    ]
