# Generated by Django 4.2.7 on 2024-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0014_retailsaveonitemsdiscountpercentage_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercategory',
            name='platform_wide',
            field=models.BooleanField(default=False),
        ),
    ]
