# Generated by Django 4.2.7 on 2024-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0015_offercategory_platform_wide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='platform_wide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
