# Generated by Django 4.2.7 on 2024-09-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0016_alter_offercategory_platform_wide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offercategory',
            name='platform_wide',
        ),
    ]
