# Generated by Django 4.2.7 on 2024-09-20 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_remove_retailproducts_sub_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0014_faqs'),
        ('retail_offers', '0017_remove_offercategory_platform_wide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('offer_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='platform_offers_banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPlatformOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentages', models.FloatField()),
                ('platform_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail_offers.platformoffer')),
                ('retail_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_platform_offer', to='retail.retailproducts')),
                ('retail_product_variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_platform_offer', to='retail.retailproductsvariations')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='vendor.vendor')),
            ],
        ),
    ]
