# Generated by Django 4.2.7 on 2024-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0021_alter_retailproducts_default_image_and_more'),
        ('retail_offers', '0018_platformoffer_vendorplatformoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorplatformoffer',
            name='retail_product',
        ),
        migrations.RemoveField(
            model_name='vendorplatformoffer',
            name='retail_product_variation',
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='retail_product',
            field=models.ManyToManyField(blank=True, related_name='vendor_platform_offer', to='retail.retailproducts'),
        ),
        migrations.AddField(
            model_name='vendorplatformoffer',
            name='retail_product_variation',
            field=models.ManyToManyField(blank=True, related_name='vendor_platform_offer', to='retail.retailproductsvariations'),
        ),
    ]
