# Generated by Django 4.2.7 on 2024-09-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0021_alter_retailproducts_default_image_and_more'),
        ('retail_offers', '0020_remove_vendorplatformoffer_retail_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorplatformoffer',
            name='retail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail.retailproducts'),
        ),
        migrations.AlterField(
            model_name='vendorplatformoffer',
            name='retail_product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_platform_offer', to='retail.retailproductsvariations'),
        ),
    ]
