# Generated by Django 4.2.7 on 2024-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0022_retailgetonefreeoffer_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoffer',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailcoupon',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailloyaltyprograms',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
