# Generated by Django 4.2.7 on 2024-09-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0024_productrequest'),
        ('menu', '0034_alter_vendorcategories_vendor_type_and_more'),
        ('retail_offers', '0023_platformoffer_disabled_retailcoupon_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='offer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='retail_offers.offercategory'),
        ),
        migrations.AlterField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='retail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproducts'),
        ),
        migrations.AlterField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='retail_product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_items', to='retail.retailproductsvariations'),
        ),
        migrations.AlterField(
            model_name='retailsaveonitemsdiscountpercentage',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_on_items', to='menu.vendorcategories'),
        ),
    ]
