# Generated by Django 4.2.7 on 2024-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_product_display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
