# Generated by Django 5.1.4 on 2024-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(choices=[('IN AMOUNT', 'IN AMOUNT'), ('IN PERCENTAGE', 'IN PERCENTAGE')], default='IN AMOUNT', help_text='\n        ("IN AMOUNT","IN AMOUNT"),\n        ("IN PERCENTAGE","IN PERCENTAGE")\n        ')),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('coupons_title', models.CharField(max_length=255)),
                ('coupon_code', models.CharField(help_text='max length = 25', max_length=25, unique=True)),
                ('coupon_type', models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Off', 'Percentage Off'), ('Delivery Fee  off', 'Delivery Fee  off')], help_text='\n        ("Flat Discount","Flat Discount"),\n        ("Percentage Off","Percentage Off"),\n        ("Delivery Fee  off","Delivery Fee  off")\n                                   ')),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('limitation_for_user', models.IntegerField()),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('charge_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FreeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='offers_banner/')),
                ('offer_name', models.CharField(default='', max_length=255, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetOneFreeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='offers_banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('offer_name', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=255, null=True, unique=True)),
                ('no_of_points', models.IntegerField()),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('in_amount', models.FloatField(default=0.0, help_text='This is the minimum amount that can be converted to loyalty points')),
                ('provided_points', models.FloatField(default=0.0, help_text='This is the amount that is provided per the amount transactions')),
                ('converted_into', models.FloatField(default=0.0, help_text='This is the amount that 1 loyalty points are converted into')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveOnItemsDiscountPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentages', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaveOnItemsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_banner', models.ImageField(null=True, upload_to='offers_banner/')),
                ('offer_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('discount_percentages', models.FloatField(default=0)),
                ('minimum_spend_amount', models.FloatField(default=0)),
                ('maximum_redeem_value', models.FloatField(default=0, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('discount_banner', models.ImageField(null=True, upload_to='offers_banner/')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
