# Generated by Django 5.0 on 2024-02-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freedelivery",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="getonefreeoffer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storeoffer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="freedelivery",
            name="audience",
            field=models.CharField(
                choices=[
                    ("New Customer", "New Customer"),
                    ("All Active Customer", "All Active Customer"),
                    ("All Customer", "All Customer"),
                ],
                help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )',
            ),
        ),
        migrations.AlterField(
            model_name="getonefreeoffer",
            name="audience",
            field=models.CharField(
                choices=[
                    ("New Customer", "New Customer"),
                    ("All Active Customer", "All Active Customer"),
                    ("All Customer", "All Customer"),
                ],
                help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )',
            ),
        ),
        migrations.AlterField(
            model_name="saveonitemsoffer",
            name="audience",
            field=models.CharField(
                choices=[
                    ("New Customer", "New Customer"),
                    ("All Active Customer", "All Active Customer"),
                    ("All Customer", "All Customer"),
                ],
                help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )',
            ),
        ),
        migrations.AlterField(
            model_name="storeoffer",
            name="audience",
            field=models.CharField(
                choices=[
                    ("New Customer", "New Customer"),
                    ("All Active Customer", "All Active Customer"),
                    ("All Customer", "All Customer"),
                ],
                help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )',
            ),
        ),
    ]
