# Generated by Django 5.0 on 2024-02-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        ("offers", "0002_freedelivery_active_getonefreeoffer_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="getonefreeoffer",
            name="item",
        ),
        migrations.RemoveField(
            model_name="saveonitemsoffer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="saveonitemsoffer",
            name="item",
        ),
        migrations.AddField(
            model_name="getonefreeoffer",
            name="item",
            field=models.ManyToManyField(to="menu.fooditem"),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="category",
            field=models.ManyToManyField(to="menu.vendorcategories"),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="item",
            field=models.ManyToManyField(to="menu.fooditem"),
        ),
    ]
