# Generated by Django 5.0 on 2024-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        ("offers", "0003_remove_getonefreeoffer_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveonitemsoffer",
            name="category",
            field=models.ManyToManyField(null=True, to="menu.vendorcategories"),
        ),
        migrations.AlterField(
            model_name="saveonitemsoffer",
            name="item",
            field=models.ManyToManyField(null=True, to="menu.fooditem"),
        ),
    ]
