# Generated by Django 5.0 on 2024-02-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        ("offers", "0004_alter_saveonitemsoffer_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveonitemsoffer",
            name="category",
            field=models.ManyToManyField(blank=True, to="menu.vendorcategories"),
        ),
        migrations.AlterField(
            model_name="saveonitemsoffer",
            name="item",
            field=models.ManyToManyField(blank=True, to="menu.fooditem"),
        ),
    ]
