# Generated by Django 5.0 on 2024-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_alter_saveonitemsoffer_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="getonefreeoffer",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="getonefreeoffer",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="freedelivery",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="freedelivery",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="storeoffer",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="storeoffer",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
