# Generated by Django 5.0 on 2024-03-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        ("offers", "0006_getonefreeoffer_end_date_getonefreeoffer_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saveonitemsoffer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="saveonitemsoffer",
            name="discount_percentage",
        ),
        migrations.RemoveField(
            model_name="saveonitemsoffer",
            name="item",
        ),
        migrations.RemoveField(
            model_name="storeoffer",
            name="discount_percentage",
        ),
        migrations.AddField(
            model_name="storeoffer",
            name="offer_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="StoreOfferDiscountPercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_percentage", models.FloatField(default=0)),
                (
                    "category",
                    models.ManyToManyField(null=True, to="menu.vendorcategories"),
                ),
                ("item", models.ManyToManyField(null=True, to="menu.fooditem")),
                (
                    "store_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offers.storeoffer",
                    ),
                ),
            ],
        ),
    ]
