# Generated by Django 5.0 on 2024-03-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        ("offers", "0007_remove_saveonitemsoffer_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeofferdiscountpercentage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="storeofferdiscountpercentage",
            name="item",
        ),
        migrations.AlterField(
            model_name="storeofferdiscountpercentage",
            name="store_offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="offers.storeoffer"
            ),
        ),
        migrations.AddField(
            model_name="storeofferdiscountpercentage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="menu.vendorcategories",
            ),
        ),
        migrations.AddField(
            model_name="storeofferdiscountpercentage",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="menu.fooditem",
            ),
        ),
    ]
