# Generated by Django 5.0 on 2024-03-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0009_alter_storeofferdiscountpercentage_store_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeofferdiscountpercentage",
            name="store_offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discount_percentage",
                to="offers.saveonitemsoffer",
            ),
        ),
    ]
