# Generated by Django 5.0 on 2024-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0010_alter_storeofferdiscountpercentage_store_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="freedelivery",
            name="discount_banner",
            field=models.ImageField(null=True, upload_to="offers_banner/"),
        ),
        migrations.AddField(
            model_name="getonefreeoffer",
            name="discount_banner",
            field=models.ImageField(null=True, upload_to="offers_banner/"),
        ),
        migrations.AddField(
            model_name="saveonitemsoffer",
            name="discount_banner",
            field=models.ImageField(null=True, upload_to="offers_banner/"),
        ),
        migrations.AddField(
            model_name="storeoffer",
            name="discount_banner",
            field=models.ImageField(null=True, upload_to="offers_banner/"),
        ),
    ]
