# Generated by Django 5.0 on 2024-03-04 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_alter_customizationtitle_select_type"),
        (
            "offers",
            "0012_rename_discount_percentage_storeofferdiscountpercentage_discount_percentages",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StoreOfferDiscountPercentage",
            new_name="SaveOnItemsDiscountPercentage",
        ),
    ]
