# Generated by Django 5.0 on 2024-03-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_rename_storeofferdiscountpercentage_saveonitemsdiscountpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveonitemsdiscountpercentage',
            name='store_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='offers.saveonitemsoffer'),
        ),
    ]
