# Generated by Django 5.0 on 2024-03-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_alter_saveonitemsdiscountpercentage_store_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeoffer',
            name='maximum_redeem_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
