# Generated by Django 5.0 on 2024-03-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_vendorcategories_active'),
        ('offers', '0015_alter_storeoffer_maximum_redeem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedelivery',
            name='offer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getonefreeoffer',
            name='offer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saveonitemsoffer',
            name='offer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saveonitemsdiscountpercentage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_item', to='menu.vendorcategories'),
        ),
        migrations.AlterField(
            model_name='saveonitemsdiscountpercentage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_on_item', to='menu.fooditem'),
        ),
        migrations.AlterField(
            model_name='saveonitemsdiscountpercentage',
            name='store_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='offers.saveonitemsoffer'),
        ),
    ]
