# Generated by Django 5.0 on 2024-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_freedelivery_offer_name_getonefreeoffer_offer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedelivery',
            name='offer_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='getonefreeoffer',
            name='offer_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
