# Generated by Django 5.0 on 2024-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_alter_freedelivery_offer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupons_title', models.CharField(max_length=255)),
                ('coupon_code', models.CharField(help_text='max length = 25', max_length=25)),
                ('coupon_type', models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Off', 'Percentage Off'), ('Delivery Fee  off', 'Delivery Fee  off')], help_text='\n        ("Flat Discount","Flat Discount"),\n        ("Percentage Off","Percentage Off"),\n        ("Delivery Fee  off","Delivery Fee  off")\n                                   ')),
                ('minimum_spend_amount', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
                ('limitation_for_user', models.IntegerField()),
                ('audience', models.CharField(choices=[('New Customer', 'New Customer'), ('All Active Customer', 'All Active Customer'), ('All Customer', 'All Customer')], help_text=' AUDIENCE = (\n    ("New Customer", "New Customer"),\n    ("All Active Customer", "All Active Customer"),\n    ("All Customer", "All Customer"),\n    )')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('charge_name', models.CharField(max_length=255)),
            ],
        ),
    ]
