# Generated by Django 5.0 on 2024-03-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_coupons_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
