# Generated by Django 5.0 on 2024-03-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_coupons_discount_amount'),
        ('vendor', '0005_rename_vendor_image_vendor_vendor_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='vendor.vendor'),
        ),
    ]
