# Generated by Django 5.0 on 2024-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_coupons_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoffer',
            name='discount_percentages',
            field=models.FloatField(default=0),
        ),
    ]
