# Generated by Django 5.0 on 2024-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_alter_coupons_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount_percentages',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coupons',
            name='discount_type',
            field=models.CharField(choices=[('IN AMOUNT', 'IN AMOUNT'), ('IN PERCENTAGE', 'IN PERCENTAGE')], default='IN AMOUNT', help_text='\n        ("IN AMOUNT","IN AMOUNT"),\n        ("IN PERCENTAGE","IN PERCENTAGE")\n        '),
        ),
    ]
