# Generated by Django 5.0 on 2024-03-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_coupons_discount_percentages_coupons_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('no_of_points', models.IntegerField()),
                ('discount_percentages', models.FloatField(default=0.0)),
                ('maximum_redeem_amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
