# Generated by Django 5.0 on 2024-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_loyaltyprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('provided_points', models.FloatField(default=0.0, help_text='This is the amount that is provided per the amount transactions')),
                ('in_amount', models.FloatField(default=0.0, help_text='This is the minimum amount that can be converted to loyalty points')),
                ('converted_into', models.FloatField(default=0.0, help_text='This is the amount that 1 loyalty points are converted into')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='updated_date',
        ),
    ]
