# Generated by Django 4.2.7 on 2024-09-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0027_vendorcategories_image_vendordepartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='homepage-content/')),
                ('title_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('hyperlink', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='menu.vendorcategories')),
                ('section_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='homepage.homepagesection')),
            ],
        ),
    ]
