# Generated by Django 4.2.7 on 2024-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
