# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('retail_product_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='retail_product_display.categorygroup'),
        ),
    ]
