# Generated by Django 4.2.7 on 2024-09-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_product_display', '0002_alter_categorygroup_group_name'),
        ('homepage', '0002_alter_homepagesection_section_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='retail_product_display.categorygroup'),
        ),
    ]
