# Generated by Django 4.2.7 on 2024-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_homepagecontent_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
