# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0003_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='homepage.homepagesection'),
        ),
    ]
