# Generated by Django 4.2.7 on 2024-09-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_product_display', '0002_alter_categorygroup_group_name'),
        ('retail_offers', '0019_remove_vendorplatformoffer_retail_product_and_more'),
        ('homepage', '0004_homepagecontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='platform_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='retail_offers.platformoffer'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='retail_product_display.categorygroup'),
        ),
    ]
