# Generated by Django 4.2.7 on 2024-10-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepagecontent_platform_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage-content/'),
        ),
    ]
