# Generated by Django 4.2.16 on 2024-12-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0014_faqs'),
        ('homepage', '0006_alter_homepagecontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='vendor.vendor'),
        ),
    ]
