# Generated by Django 4.2.16 on 2024-12-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_homepagecontent_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=100, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads-section/')),
                ('hyperlink', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
