# Generated by Django 5.1.4 on 2024-12-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_adssection"),
    ]

    operations = [
        migrations.AddField(
            model_name="adssection",
            name="image_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adssection",
            name="image_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
