# Generated by Django 4.2.7 on 2024-07-25 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail', '0009_alter_productsvariationsimage_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50, null=True)),
                ('special_request', models.CharField(max_length=255, null=True)),
                ('receiver_name', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('retail_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_carts', to='retail.retailproducts')),
                ('retail_product_variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_carts', to='retail.retailproductsvariations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
