# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.IntegerField(default=0)),
                ('max_distance', models.IntegerField(default=0)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50, null=True)),
                ('special_request', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('buy_now', models.BooleanField(blank=True, default=False, null=True)),
                ('retail_product_variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_carts', to='retail.retailproductsvariations')),
            ],
        ),
    ]
