# Generated by Django 4.2.7 on 2024-08-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailcart',
            name='retail_product',
        ),
    ]
