# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail_marketplace', '0001_initial'),
        ('retail_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcart',
            name='shared_wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='retail_wishlist.sharedretailwishlist'),
        ),
    ]
