# Generated by Django 4.2.7 on 2024-08-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0003_sharedretailwishlist'),
        ('retail_marketplace', '0002_remove_retailcart_retail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcart',
            name='shared_wislist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='retail_wishlist.sharedretailwishlist'),
        ),
    ]
