# Generated by Django 4.2.7 on 2024-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0003_retailcart_shared_wislist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailcart',
            old_name='shared_wislist',
            new_name='shared_wishlist',
        ),
    ]
