# Generated by Django 4.2.7 on 2024-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0004_rename_shared_wislist_retailcart_shared_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0.0)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
