# Generated by Django 4.2.7 on 2024-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0005_retaildeliverycharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaildeliverycharge',
            name='distance',
        ),
        migrations.AddField(
            model_name='retaildeliverycharge',
            name='max_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retaildeliverycharge',
            name='min_distance',
            field=models.IntegerField(default=0),
        ),
    ]
