# Generated by Django 4.2.7 on 2024-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0006_remove_retaildeliverycharge_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcart',
            name='buy_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
