# Generated by Django 4.2.7 on 2024-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='review',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='review-image/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='review-image/'),
        ),
    ]
