# Generated by Django 4.2.7 on 2024-11-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0009_rename_image_review_image_1_review_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_3',
        ),
    ]
