# Generated by Django 4.2.7 on 2024-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0010_rename_image_1_review_image_remove_review_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='review',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='review-image/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='review-image/'),
        ),
    ]
