# Generated by Django 4.2.16 on 2024-11-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0011_rename_image_review_image_1_review_image_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
