# Generated by Django 4.2.16 on 2024-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0012_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailcart',
            name='special_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
