# Generated by Django 4.2.7 on 2024-08-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailwishlist',
            name='quantity',
        ),
    ]
