# Generated by Django 4.2.7 on 2024-08-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0003_sharedretailwishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedretailwishlist',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
