# Generated by Django 4.2.16 on 2024-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0005_userretailwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedretailwishlist',
            name='nation',
            field=models.CharField(blank=True, default='NP', max_length=5, null=True),
        ),
    ]
