# Generated by Django 4.2.16 on 2024-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0006_sharedretailwishlist_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailwishlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
