# Generated by Django 4.2.16 on 2024-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_wishlist', '0007_retailwishlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedretailwishlist',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
