# Generated by Django 5.0 on 2024-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_login",
            field=models.BooleanField(default=False),
        ),
    ]
