# Generated by Django 5.0 on 2024-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userlocation_address_userlocation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.FloatField(default=0.0),
        ),
    ]
