# Generated by Django 5.0 on 2024-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_user',
            field=models.BooleanField(default=False),
        ),
    ]
