# Generated by Django 4.2.7 on 2024-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userlocation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='applied_coupon',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
