# Generated by Django 4.2.7 on 2024-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
