# Generated by Django 4.2.7 on 2024-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userlocation_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
