# Generated by Django 4.2.7 on 2024-10-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userlocation_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_setup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
