# Generated by Django 4.2.7 on 2024-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_profile_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='nation',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('US', 'US')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nation',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('US', 'US')], max_length=5, null=True),
        ),
    ]
