# Generated by Django 5.0 on 2024-07-14 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0026_customization_customization_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailVariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='retail-products/')),
                ('discountable', models.BooleanField(default=False)),
                ('age_restriction', models.BooleanField(default=False)),
                ('product_unique_id', models.UUIDField(default=uuid.UUID('8d622a66-7d73-4240-aa7e-ffe0a158afd5'))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='menu.vendordepartment')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='menu.vendorcategories')),
            ],
        ),
        migrations.CreateModel(
            name='RetailProductsVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stock_quantity', models.PositiveBigIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_variations', to='retail.retailproducts')),
                ('variation', models.ManyToManyField(related_name='products', to='retail.retailvariation')),
            ],
        ),
        migrations.AddField(
            model_name='retailvariation',
            name='variation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='retail.retailvariationtype'),
        ),
    ]
