# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_initial'),
        ('retail', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productsvariationsimage',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='menu.vendordepartment'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='refund_policies',
            field=models.ManyToManyField(to='retail.refundpolicy'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='menu.vendorcategories'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_retails', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_variations', to='retail.retailproducts'),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='variations_image',
            field=models.ManyToManyField(blank=True, related_name='variations', to='retail.productsvariationsimage'),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='variation',
            field=models.ManyToManyField(blank=True, related_name='products', to='retail.retailvariation'),
        ),
        migrations.AddField(
            model_name='retailvariation',
            name='variation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='retail.retailvariationtype'),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_keyword', to=settings.AUTH_USER_MODEL),
        ),
    ]
