# Generated by Django 5.0 on 2024-07-14 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='product_unique_id',
            field=models.UUIDField(default=uuid.UUID('b912ba86-6026-4dca-9c36-89a7120ffdbe')),
        ),
    ]
