# Generated by Django 5.0 on 2024-07-14 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_retailproducts_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproducts',
            name='product_unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
