# Generated by Django 5.0 on 2024-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_alter_retailproducts_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
