# Generated by Django 5.0 on 2024-07-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_retailproducts_price_retailproductsvariations_price'),
        ('vendor', '0014_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_retails', to='vendor.vendor'),
        ),
    ]
