# Generated by Django 5.0 on 2024-07-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_retailproducts_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailproducts',
            name='price',
        ),
        migrations.AlterField(
            model_name='retailproductsvariations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductsVariationsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='retail-products-variations/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations_image', to='retail.retailproductsvariations')),
            ],
        ),
    ]
