# Generated by Django 5.0 on 2024-07-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_remove_retailproducts_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailproducts',
            old_name='image',
            new_name='default_image',
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='image_1',
            field=models.ImageField(null=True, upload_to='retail-products/'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='image_2',
            field=models.ImageField(null=True, upload_to='retail-products/'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='image_3',
            field=models.ImageField(null=True, upload_to='retail-products/'),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='image_4',
            field=models.ImageField(null=True, upload_to='retail-products/'),
        ),
    ]
