# Generated by Django 5.0 on 2024-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_rename_image_retailproducts_default_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproductsvariations',
            name='specifications',
            field=models.JSONField(null=True),
        ),
    ]
