# Generated by Django 4.2.7 on 2024-08-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0009_alter_productsvariationsimage_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailproducts",
            name="image_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="retail-products/"
            ),
        ),
        migrations.AlterField(
            model_name="retailproducts",
            name="image_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="retail-products/"
            ),
        ),
        migrations.AlterField(
            model_name="retailproducts",
            name="image_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="retail-products/"
            ),
        ),
        migrations.AlterField(
            model_name="retailproducts",
            name="image_4",
            field=models.ImageField(
                blank=True, null=True, upload_to="retail-products/"
            ),
        ),
        migrations.AlterField(
            model_name="retailproductsvariations",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retailvariation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retailvariationtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
