# Generated by Django 4.2.7 on 2024-08-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_alter_retailproducts_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='tax_exclusive_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
