# Generated by Django 4.2.7 on 2024-08-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_retailproducts_tax_exempt_retailproducts_tax_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailproductsvariations',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='retailproductsvariations',
            name='tax_exclusive_price',
        ),
    ]
