# Generated by Django 4.2.7 on 2024-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0012_remove_retailproductsvariations_tax_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsvariationsimage',
            name='variation',
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='variations_image',
            field=models.ManyToManyField(related_name='variations', to='retail.productsvariationsimage'),
        ),
    ]
