# Generated by Django 4.2.7 on 2024-09-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_refundpolicy_retailproducts_refund_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
