# Generated by Django 4.2.7 on 2024-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_vendorcategories_image_vendordepartment_image'),
        ('retail', '0015_alter_refundpolicy_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailproducts',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='sub_category',
            field=models.ManyToManyField(related_name='retail_products', to='menu.vendorcategories'),
        ),
    ]
