# Generated by Django 4.2.7 on 2024-09-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_vendorcategories_image_vendordepartment_image'),
        ('retail', '0016_remove_retailproducts_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailproducts',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='menu.vendorcategories'),
            preserve_default=False,
        ),
    ]
