# Generated by Django 4.2.7 on 2024-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_alter_retailproducts_default_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproductsvariations',
            name='variation',
            field=models.ManyToManyField(blank=True, related_name='products', to='retail.retailvariation'),
        ),
        migrations.AlterField(
            model_name='retailproductsvariations',
            name='variations_image',
            field=models.ManyToManyField(blank=True, related_name='variations', to='retail.productsvariationsimage'),
        ),
    ]
