# Generated by Django 4.2.7 on 2024-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0019_alter_retailproductsvariations_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproducts',
            name='default_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
