# Generated by Django 4.2.7 on 2024-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0020_alter_retailproducts_default_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproducts',
            name='default_image',
            field=models.ImageField(null=True, upload_to='retail_products/'),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='retail_products/'),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='retail_products/'),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='retail_products/'),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='retail_products/'),
        ),
    ]
