# Generated by Django 4.2.7 on 2024-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0021_alter_retailproducts_default_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsvariationsimage',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailproducts',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailproductsvariations',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailvariation',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailvariationtype',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
