# Generated by Django 4.2.7 on 2024-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0022_productsvariationsimage_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproducts',
            name='name',
            field=models.TextField(),
        ),
    ]
