# Generated by Django 4.2.7 on 2024-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0024_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retailproducts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
