# Generated by Django 4.2.7 on 2024-10-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0014_faqs'),
        ('retail', '0025_retailproducts_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsvariationsimage',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
