# Generated by Django 4.2.16 on 2024-11-21 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail', '0027_searchkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_keyword', to=settings.AUTH_USER_MODEL),
        ),
    ]
