# Generated by Django 4.2.16 on 2024-12-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0029_retailproducts_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailproducts',
            name='special_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
