# Generated by Django 5.1.4 on 2024-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0030_retailproducts_special_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailproducts",
            name="delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same day", "same day"),
                    ("1-2 days", "1-2 days"),
                    ("3-5 days", "3-5 days"),
                    ("5-7 days", "5-7 days"),
                ],
                default="same day",
                max_length=50,
                null=True,
            ),
        ),
    ]
