# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='customizationtitle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='customization',
            name='customization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_customization', to='menu.customizationtitle'),
        ),
        migrations.AddField(
            model_name='customization',
            name='customization_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.customizationtitle'),
        ),
        migrations.AddField(
            model_name='foodaddonsfoodjunction',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_addons', to='menu.customizationtitle'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='hours_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorhourtimelines'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='foodaddonsfoodjunction',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem'),
        ),
        migrations.AddField(
            model_name='vendorcategories',
            name='hours_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorhourtimelines'),
        ),
        migrations.AddField(
            model_name='vendorcategories',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.vendorcategories'),
        ),
        migrations.AddField(
            model_name='vendordepartment',
            name='hours_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorhourtimelines'),
        ),
        migrations.AddField(
            model_name='vendordepartment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='vendorcategories',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='menu.vendordepartment'),
        ),
    ]
