# Generated by Django 5.0 on 2023-12-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodaddonscategory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
        migrations.AddField(
            model_name="foodaddons",
            name="food_addons",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.foodaddonscategory",
            ),
        ),
        migrations.AddField(
            model_name="foodaddonsfoodjunction",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_addons",
                to="menu.foodaddonscategory",
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_item",
                to="menu.category",
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendor.vendor"
            ),
        ),
        migrations.AddField(
            model_name="foodaddonsfoodjunction",
            name="food_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.fooditem"
            ),
        ),
        migrations.AddField(
            model_name="foodaddonscategory",
            name="food_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.fooditem",
            ),
        ),
    ]
