# Generated by Django 5.0 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaddons",
            name="categories",
        ),
        migrations.AddField(
            model_name="foodaddons",
            name="description",
            field=models.CharField(
                help_text="This is the description for the addons, max_length = 255",
                max_length=225,
                null=True,
            ),
        ),
    ]
