# Generated by Django 5.0 on 2024-01-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_remove_foodaddons_categories_foodaddons_description"),
        ("vendor", "0002_vendor_age_restriction_vendor_tax_exempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                ("department_slug", models.SlugField()),
                ("tax_rate", models.FloatField(default=0.0)),
                ("tax_exempt", models.BooleanField(default=False)),
                ("age_restriction", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendor.vendor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fooditem",
            name="vendor_categories",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.vendorcategories",
            ),
        ),
        migrations.CreateModel(
            name="VendorDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(help_text="Department name", max_length=255),
                ),
                ("department_slug", models.SlugField()),
                ("tax_rate", models.FloatField(default=0.0)),
                ("tax_exempt", models.BooleanField(default=False)),
                ("age_restriction", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendor.vendor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vendorcategories",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.vendordepartment"
            ),
        ),
    ]
