# Generated by Django 5.0 on 2024-01-18 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_vendorcategories_fooditem_vendor_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendorcategories",
            old_name="department_slug",
            new_name="category_slug",
        ),
    ]
