# Generated by Django 5.0 on 2024-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_rename_department_slug_vendorcategories_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorcategories",
            name="category_description",
            field=models.TextField(null=True),
        ),
    ]
