# Generated by Django 5.0 on 2024-02-03 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_vendorcategories_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
