# Generated by Django 5.0 on 2024-02-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_remove_fooditem_category_delete_category"),
        ("vendor", "0004_vendor_vendor_image_vendor_vendor_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="hours_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendorhourtimelines",
            ),
        ),
        migrations.AddField(
            model_name="vendorcategories",
            name="hours_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendorhourtimelines",
            ),
        ),
        migrations.AddField(
            model_name="vendordepartment",
            name="hours_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendorhourtimelines",
            ),
        ),
    ]
