# Generated by Django 5.0 on 2024-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0008_fooditem_hours_schedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaddonscategory",
            name="food_item",
        ),
        migrations.AddField(
            model_name="foodaddonscategory",
            name="food_item",
            field=models.ManyToManyField(null=True, to="menu.fooditem"),
        ),
    ]
