# Generated by Django 5.0 on 2024-02-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0009_remove_foodaddonscategory_food_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodaddonscategory",
            name="food_item",
            field=models.ManyToManyField(to="menu.fooditem"),
        ),
    ]
