# Generated by Django 5.0 on 2024-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0010_alter_foodaddonscategory_food_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodaddons",
            name="maximum_number",
            field=models.IntegerField(default=0),
        ),
    ]
