# Generated by Django 5.0 on 2024-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0011_foodaddons_maximum_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodaddons",
            name="multiple_orders",
            field=models.BooleanField(default=False),
        ),
    ]
