# Generated by Django 5.0 on 2024-02-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0012_foodaddons_multiple_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaddonscategory",
            name="food_item",
        ),
        migrations.AddField(
            model_name="foodaddonscategory",
            name="customization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sec_customization",
                to="menu.foodaddonscategory",
            ),
        ),
        migrations.AddField(
            model_name="foodaddonscategory",
            name="secondary_customization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="foodaddonsfoodjunction",
            name="food_addons_order",
            field=models.IntegerField(default=0),
        ),
    ]
