# Generated by Django 5.0 on 2024-02-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0013_remove_foodaddonscategory_food_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaddonscategory",
            name="customization",
        ),
        migrations.RemoveField(
            model_name="foodaddonscategory",
            name="secondary_customization",
        ),
        migrations.AddField(
            model_name="foodaddons",
            name="customization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sec_customization",
                to="menu.foodaddons",
            ),
        ),
        migrations.AddField(
            model_name="foodaddons",
            name="secondary_customization",
            field=models.BooleanField(default=False),
        ),
    ]
