# Generated by Django 5.0 on 2024-02-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0014_remove_foodaddonscategory_customization_and_more"),
        ("vendor", "0005_rename_vendor_image_vendor_vendor_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodaddons",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodaddonsfoodjunction",
            unique_together={("food_item", "categories")},
        ),
    ]
