# Generated by Django 5.0 on 2024-02-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0015_foodaddons_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodaddons",
            name="customization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sec_customization",
                to="menu.foodaddonscategory",
            ),
        ),
    ]
