# Generated by Django 5.0 on 2024-02-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_remove_cartaddons_addons"),
        ("menu", "0016_alter_foodaddons_customization"),
        ("vendor", "0005_rename_vendor_image_vendor_vendor_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaddonscategory",
            name="created_by",
        ),
        migrations.CreateModel(
            name="CustomizationTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minimum_quantity", models.PositiveSmallIntegerField()),
                ("maximum_quantity", models.FloatField()),
                ("multiple_selection", models.BooleanField(default=False)),
                ("add_on_category", models.CharField(max_length=255)),
                (
                    "select_type",
                    models.CharField(
                        choices=[("SINGLE", "SINGLE"), ("MUlTIPLE", "MULTIPLE")],
                        default="SINGLE",
                        max_length=225,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("maximum_number", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(
                        help_text="This is the description for the addons, max_length = 255",
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="addons/"),
                ),
                ("secondary_customization", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor.vendor",
                    ),
                ),
                (
                    "customization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sec_customization",
                        to="menu.customizationtitle",
                    ),
                ),
                (
                    "customization_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.customizationtitle",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="foodaddonsfoodjunction",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_addons",
                to="menu.customizationtitle",
            ),
        ),
        migrations.DeleteModel(
            name="FoodAddons",
        ),
        migrations.DeleteModel(
            name="FoodAddOnsCategory",
        ),
    ]
