# Generated by Django 5.0 on 2024-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0017_remove_foodaddonscategory_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customizationtitle",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
