# Generated by Django 5.0 on 2024-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0018_customizationtitle_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customizationtitle",
            name="select_type",
            field=models.CharField(
                choices=[("SINGLE", "SINGLE"), ("MULTIPLE", "MULTIPLE")],
                default="SINGLE",
                max_length=225,
            ),
        ),
    ]
