# Generated by Django 5.0 on 2024-03-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_alter_customizationtitle_select_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationtitle',
            name='multiple_selection',
        ),
        migrations.AddField(
            model_name='customization',
            name='multiple_selection',
            field=models.BooleanField(default=False),
        ),
    ]
