# Generated by Django 5.0 on 2024-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_customizationtitle_multiple_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcategories',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
