# Generated by Django 5.0 on 2024-04-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_vendorcategories_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_item_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorcategories',
            name='categories_order',
            field=models.IntegerField(default=0),
        ),
    ]
