# Generated by Django 5.0 on 2024-04-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_fooditem_food_item_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodaddonsfoodjunction',
            name='food_addons_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendorcategories',
            name='categories_order',
            field=models.IntegerField(default=1),
        ),
    ]
