# Generated by Django 5.0 on 2024-05-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_foodaddonsfoodjunction_food_addons_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategories',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.vendordepartment'),
        ),
    ]
