# Generated by Django 5.0 on 2024-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_foodaddonsfoodjunction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='customization_order',
            field=models.IntegerField(default=1),
        ),
    ]
