# Generated by Django 4.2.7 on 2024-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_customization_customization_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='department/'),
        ),
        migrations.AddField(
            model_name='vendordepartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='department/'),
        ),
    ]
