# Generated by Django 4.2.7 on 2024-09-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0014_faqs"),
        ("menu", "0027_vendorcategories_image_vendordepartment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorcategories",
            name="hours_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendorhourtimelines",
            ),
        ),
    ]
