# Generated by Django 4.2.7 on 2024-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_vendordepartment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordepartment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
