# Generated by Django 4.2.7 on 2024-09-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_vendordepartment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordepartment',
            name='is_active',
        ),
    ]
