# Generated by Django 5.0 on 2024-09-20 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0028_alter_vendorcategories_hours_schedule"),
        ("menu", "0030_remove_vendordepartment_is_active"),
    ]

    operations = []
