# Generated by Django 4.2.7 on 2024-09-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0014_faqs'),
        ('menu', '0031_merge_20240920_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordepartment',
            name='hours_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorhourtimelines'),
        ),
    ]
