# Generated by Django 4.2.7 on 2024-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_alter_vendordepartment_hours_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcategories',
            name='vendor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Retails')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='vendordepartment',
            name='vendor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Retails')], default=1, null=True),
        ),
    ]
