# Generated by Django 4.2.7 on 2024-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_vendorcategories_vendor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategories',
            name='vendor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Retails')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendordepartment',
            name='vendor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Retails')], default=2, null=True),
        ),
    ]
