# Generated by Django 4.2.7 on 2024-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_alter_vendorcategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendordepartment',
            options={'ordering': ['department_order']},
        ),
        migrations.AddField(
            model_name='vendordepartment',
            name='department_order',
            field=models.IntegerField(default=0),
        ),
    ]
