# Generated by Django 4.2.16 on 2024-12-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_alter_vendordepartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcategories',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='menu.vendordepartment'),
        ),
    ]
