# Generated by Django 5.0 on 2024-04-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_loyaltyprograms'),
        ('orders', '0002_alter_order_order_number'),
        ('vendor', '0005_rename_vendor_image_vendor_vendor_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('discounted_amount', models.FloatField(default=0.0)),
                ('addons_cost', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('coupon_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_used', to='offers.coupons')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vendor', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='vendor.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='vendor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_food', to='orders.vendorsorders'),
        ),
    ]
