# Generated by Django 5.0 on 2024-04-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_loyaltyprograms'),
        ('orders', '0003_vendorsorders_orderedfood_vendor_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsorders',
            name='coupon_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_used', to='offers.coupons'),
        ),
    ]
