# Generated by Django 5.0 on 2024-04-18 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_vendorsorders_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('RazorPay', 'RazorPay'), ('Stripe', 'Stripe')], max_length=100),
        ),
    ]
