# Generated by Django 5.0 on 2024-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_loyalty_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='cart_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
