# Generated by Django 5.0 on 2024-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderedfood_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoices',
            name='tax_data',
        ),
        migrations.AddField(
            model_name='vendorinvoices',
            name='total_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='vendorinvoices',
            name='ordered_food',
        ),
        migrations.AddField(
            model_name='vendorinvoices',
            name='ordered_food',
            field=models.ManyToManyField(to='orders.orderedfood'),
        ),
    ]
