# Generated by Django 5.0 on 2024-04-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_vendorinvoices_tax_data_and_more'),
        ('vendor', '0007_alter_vendorhourtimelines_week_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoices',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='vendor.vendor'),
        ),
    ]
