# Generated by Django 5.0 on 2024-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_loyalty_points_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomization',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
