# Generated by Django 5.0 on 2024-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_ordercustomization_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
