# Generated by Django 4.2.7 on 2024-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_order_payment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
