# Generated by Django 4.2.7 on 2024-08-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0008_retailcoupon_chowchow_coupon'),
        ('vendor', '0014_faqs'),
        ('retail_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailVendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('discounted_amount', models.FloatField(default=0.0)),
                ('addons_cost', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('coupon_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_coupon_used', to='retail_offers.retailcoupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_order_vendor', to='retail_orders.retailorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_retail_orders', to='vendor.vendor')),
            ],
        ),
    ]
