# Generated by Django 5.1.4 on 2024-12-23 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail_logistics', '0002_initial'),
        ('retail_marketplace', '0003_initial'),
        ('retail_offers', '0002_initial'),
        ('retail_orders', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductstatus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='retail_logistics.deliverydriver'),
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='ordered_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='retail_orders.orderedproduct'),
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='carts',
            field=models.ManyToManyField(related_name='orders', to='retail_marketplace.retailcart'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='loyalty_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_loyalty_orders', to='retail_offers.retailloyaltyprograms'),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='retail_orders.retailorder'),
        ),
        migrations.AddField(
            model_name='retailpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail_orders.retailpayment'),
        ),
        migrations.AddField(
            model_name='retailpaymentinfo',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='retail_orders.retailpayment'),
        ),
        migrations.AddField(
            model_name='retailvendororder',
            name='coupon_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_coupon_used', to='retail_offers.retailcoupon'),
        ),
        migrations.AddField(
            model_name='retailvendororder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_order_vendor', to='retail_orders.retailorder'),
        ),
        migrations.AddField(
            model_name='retailvendororder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_retail_orders', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='vendor_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='retail_orders.retailvendororder'),
        ),
    ]
