# Generated by Django 4.2.7 on 2024-08-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0002_retailvendororder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailvendororder',
            name='addons_cost',
        ),
    ]
