# Generated by Django 4.2.7 on 2024-08-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_remove_productsvariationsimage_variation_and_more'),
        ('retail_orders', '0003_remove_retailvendororder_addons_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailvendororder',
            old_name='discounted_amount',
            new_name='admin_coupon_discount',
        ),
        migrations.AddField(
            model_name='retailvendororder',
            name='total_discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retailvendororder',
            name='vendor_coupon_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('discounted_amount', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('tax_exclusive_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_foods', to='retail_orders.retailorder')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailproductsvariations')),
            ],
        ),
    ]
