# Generated by Django 4.2.7 on 2024-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_marketplace', '0004_rename_shared_wislist_retailcart_shared_wishlist'),
        ('retail_orders', '0004_rename_discounted_amount_retailvendororder_admin_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='carts',
            field=models.ManyToManyField(related_name='orders', to='retail_marketplace.retailcart'),
        ),
    ]
