# Generated by Django 4.2.7 on 2024-08-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_offers', '0009_retailloyaltyprograms'),
        ('retail_orders', '0005_retailorder_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='loyalty_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_loyalty_orders', to='retail_offers.retailloyaltyprograms'),
        ),
    ]
