# Generated by Django 4.2.7 on 2024-08-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0006_retailorder_loyalty_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailorder',
            name='delivery_date',
        ),
    ]
