# Generated by Django 4.2.7 on 2024-08-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0007_remove_retailorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='vendor_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='retail_orders.retailvendororder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='retail_orders.retailorder'),
        ),
    ]
