# Generated by Django 4.2.7 on 2024-09-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail_logistics', '0002_deliverydriver_license_image'),
        ('retail_orders', '0009_orderstatus_orderedproductstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductstatus',
            name='delivery_driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='retail_logistics.deliverydriver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
