# Generated by Django 4.2.7 on 2024-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0011_orderstatus_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='closed',
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
