# Generated by Django 4.2.7 on 2024-09-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_logistics', '0004_deliverydriverstatus_created_by_and_more'),
        ('retail_orders', '0013_orderstatus_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='retail_logistics.deliverydriver'),
        ),
    ]
