# Generated by Django 4.2.7 on 2024-09-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail_orders', '0014_alter_orderedproductstatus_delivery_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='created_by',
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
