# Generated by Django 4.2.7 on 2024-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0015_remove_orderstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
