# Generated by Django 4.2.7 on 2024-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0016_alter_orderstatus_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='coupon_discount_amount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='loyalty_discount_amount',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
