# Generated by Django 4.2.7 on 2024-09-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0017_orderedproduct_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='coupon_discount_amount',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='loyalty_discount_amount',
        ),
    ]
