# Generated by Django 4.2.7 on 2024-09-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0018_remove_orderedproduct_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailvendororder',
            name='loyalty_discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
