# Generated by Django 4.2.7 on 2024-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0020_retailvendororder_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailvendororder',
            name='delivery_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
