# Generated by Django 4.2.7 on 2024-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0021_retailvendororder_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailpayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('esewa', 'Esewa'), ('cash on delivery', 'Cash On Delivery')], max_length=100),
        ),
    ]
