# Generated by Django 4.2.7 on 2024-10-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0022_alter_retailpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailpayment',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Esewa', 'Esewa'), ('Cash On Delivery', 'Cash On Delivery')], max_length=100),
        ),
    ]
