# Generated by Django 4.2.7 on 2024-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0023_alter_retailpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
