# Generated by Django 4.2.16 on 2024-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0024_alter_orderedproductstatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailorder',
            name='nation',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('US', 'US')], default='NP', max_length=5, null=True),
        ),
    ]
