# Generated by Django 4.2.16 on 2024-11-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0026_orderedproduct_ordered_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
