# Generated by Django 4.2.16 on 2024-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0027_alter_retailorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
