# Generated by Django 4.2.16 on 2024-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0030_remove_orderedproductstatus_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductstatus',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
